/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SuporteRouteImport } from './routes/suporte'
import { Route as ManualRouteImport } from './routes/manual'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ClubesRouteImport } from './routes/clubes'
import { Route as CadastroRouteImport } from './routes/cadastro'
import { Route as AvaliacoesRouteImport } from './routes/avaliacoes'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PeneirasIndexRouteImport } from './routes/peneiras.index'
import { Route as CandidatosIndexRouteImport } from './routes/candidatos.index'
import { Route as PeneirasCriarRouteImport } from './routes/peneiras.criar'
import { Route as PeneirasPeneiraIdRouteImport } from './routes/peneiras.$peneiraId'
import { Route as CandidatosCandidatoIdRouteImport } from './routes/candidatos.$candidatoId'
import { Route as CadastroClubeRouteImport } from './routes/cadastro.clube'
import { Route as CadastroAdminRouteImport } from './routes/cadastro.admin'

const SuporteRoute = SuporteRouteImport.update({
  id: '/suporte',
  path: '/suporte',
  getParentRoute: () => rootRouteImport,
} as any)
const ManualRoute = ManualRouteImport.update({
  id: '/manual',
  path: '/manual',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ClubesRoute = ClubesRouteImport.update({
  id: '/clubes',
  path: '/clubes',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroRoute = CadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const AvaliacoesRoute = AvaliacoesRouteImport.update({
  id: '/avaliacoes',
  path: '/avaliacoes',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PeneirasIndexRoute = PeneirasIndexRouteImport.update({
  id: '/peneiras/',
  path: '/peneiras/',
  getParentRoute: () => rootRouteImport,
} as any)
const CandidatosIndexRoute = CandidatosIndexRouteImport.update({
  id: '/candidatos/',
  path: '/candidatos/',
  getParentRoute: () => rootRouteImport,
} as any)
const PeneirasCriarRoute = PeneirasCriarRouteImport.update({
  id: '/peneiras/criar',
  path: '/peneiras/criar',
  getParentRoute: () => rootRouteImport,
} as any)
const PeneirasPeneiraIdRoute = PeneirasPeneiraIdRouteImport.update({
  id: '/peneiras/$peneiraId',
  path: '/peneiras/$peneiraId',
  getParentRoute: () => rootRouteImport,
} as any)
const CandidatosCandidatoIdRoute = CandidatosCandidatoIdRouteImport.update({
  id: '/candidatos/$candidatoId',
  path: '/candidatos/$candidatoId',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroClubeRoute = CadastroClubeRouteImport.update({
  id: '/clube',
  path: '/clube',
  getParentRoute: () => CadastroRoute,
} as any)
const CadastroAdminRoute = CadastroAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => CadastroRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/avaliacoes': typeof AvaliacoesRoute
  '/cadastro': typeof CadastroRouteWithChildren
  '/clubes': typeof ClubesRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/manual': typeof ManualRoute
  '/suporte': typeof SuporteRoute
  '/cadastro/admin': typeof CadastroAdminRoute
  '/cadastro/clube': typeof CadastroClubeRoute
  '/candidatos/$candidatoId': typeof CandidatosCandidatoIdRoute
  '/peneiras/$peneiraId': typeof PeneirasPeneiraIdRoute
  '/peneiras/criar': typeof PeneirasCriarRoute
  '/candidatos/': typeof CandidatosIndexRoute
  '/peneiras/': typeof PeneirasIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/avaliacoes': typeof AvaliacoesRoute
  '/cadastro': typeof CadastroRouteWithChildren
  '/clubes': typeof ClubesRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/manual': typeof ManualRoute
  '/suporte': typeof SuporteRoute
  '/cadastro/admin': typeof CadastroAdminRoute
  '/cadastro/clube': typeof CadastroClubeRoute
  '/candidatos/$candidatoId': typeof CandidatosCandidatoIdRoute
  '/peneiras/$peneiraId': typeof PeneirasPeneiraIdRoute
  '/peneiras/criar': typeof PeneirasCriarRoute
  '/candidatos': typeof CandidatosIndexRoute
  '/peneiras': typeof PeneirasIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/avaliacoes': typeof AvaliacoesRoute
  '/cadastro': typeof CadastroRouteWithChildren
  '/clubes': typeof ClubesRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/manual': typeof ManualRoute
  '/suporte': typeof SuporteRoute
  '/cadastro/admin': typeof CadastroAdminRoute
  '/cadastro/clube': typeof CadastroClubeRoute
  '/candidatos/$candidatoId': typeof CandidatosCandidatoIdRoute
  '/peneiras/$peneiraId': typeof PeneirasPeneiraIdRoute
  '/peneiras/criar': typeof PeneirasCriarRoute
  '/candidatos/': typeof CandidatosIndexRoute
  '/peneiras/': typeof PeneirasIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/avaliacoes'
    | '/cadastro'
    | '/clubes'
    | '/dashboard'
    | '/login'
    | '/manual'
    | '/suporte'
    | '/cadastro/admin'
    | '/cadastro/clube'
    | '/candidatos/$candidatoId'
    | '/peneiras/$peneiraId'
    | '/peneiras/criar'
    | '/candidatos/'
    | '/peneiras/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/avaliacoes'
    | '/cadastro'
    | '/clubes'
    | '/dashboard'
    | '/login'
    | '/manual'
    | '/suporte'
    | '/cadastro/admin'
    | '/cadastro/clube'
    | '/candidatos/$candidatoId'
    | '/peneiras/$peneiraId'
    | '/peneiras/criar'
    | '/candidatos'
    | '/peneiras'
  id:
    | '__root__'
    | '/'
    | '/avaliacoes'
    | '/cadastro'
    | '/clubes'
    | '/dashboard'
    | '/login'
    | '/manual'
    | '/suporte'
    | '/cadastro/admin'
    | '/cadastro/clube'
    | '/candidatos/$candidatoId'
    | '/peneiras/$peneiraId'
    | '/peneiras/criar'
    | '/candidatos/'
    | '/peneiras/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AvaliacoesRoute: typeof AvaliacoesRoute
  CadastroRoute: typeof CadastroRouteWithChildren
  ClubesRoute: typeof ClubesRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  ManualRoute: typeof ManualRoute
  SuporteRoute: typeof SuporteRoute
  CandidatosCandidatoIdRoute: typeof CandidatosCandidatoIdRoute
  PeneirasPeneiraIdRoute: typeof PeneirasPeneiraIdRoute
  PeneirasCriarRoute: typeof PeneirasCriarRoute
  CandidatosIndexRoute: typeof CandidatosIndexRoute
  PeneirasIndexRoute: typeof PeneirasIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/suporte': {
      id: '/suporte'
      path: '/suporte'
      fullPath: '/suporte'
      preLoaderRoute: typeof SuporteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manual': {
      id: '/manual'
      path: '/manual'
      fullPath: '/manual'
      preLoaderRoute: typeof ManualRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clubes': {
      id: '/clubes'
      path: '/clubes'
      fullPath: '/clubes'
      preLoaderRoute: typeof ClubesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro': {
      id: '/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof CadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/avaliacoes': {
      id: '/avaliacoes'
      path: '/avaliacoes'
      fullPath: '/avaliacoes'
      preLoaderRoute: typeof AvaliacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/peneiras/': {
      id: '/peneiras/'
      path: '/peneiras'
      fullPath: '/peneiras/'
      preLoaderRoute: typeof PeneirasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/candidatos/': {
      id: '/candidatos/'
      path: '/candidatos'
      fullPath: '/candidatos/'
      preLoaderRoute: typeof CandidatosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/peneiras/criar': {
      id: '/peneiras/criar'
      path: '/peneiras/criar'
      fullPath: '/peneiras/criar'
      preLoaderRoute: typeof PeneirasCriarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/peneiras/$peneiraId': {
      id: '/peneiras/$peneiraId'
      path: '/peneiras/$peneiraId'
      fullPath: '/peneiras/$peneiraId'
      preLoaderRoute: typeof PeneirasPeneiraIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/candidatos/$candidatoId': {
      id: '/candidatos/$candidatoId'
      path: '/candidatos/$candidatoId'
      fullPath: '/candidatos/$candidatoId'
      preLoaderRoute: typeof CandidatosCandidatoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro/clube': {
      id: '/cadastro/clube'
      path: '/clube'
      fullPath: '/cadastro/clube'
      preLoaderRoute: typeof CadastroClubeRouteImport
      parentRoute: typeof CadastroRoute
    }
    '/cadastro/admin': {
      id: '/cadastro/admin'
      path: '/admin'
      fullPath: '/cadastro/admin'
      preLoaderRoute: typeof CadastroAdminRouteImport
      parentRoute: typeof CadastroRoute
    }
  }
}

interface CadastroRouteChildren {
  CadastroAdminRoute: typeof CadastroAdminRoute
  CadastroClubeRoute: typeof CadastroClubeRoute
}

const CadastroRouteChildren: CadastroRouteChildren = {
  CadastroAdminRoute: CadastroAdminRoute,
  CadastroClubeRoute: CadastroClubeRoute,
}

const CadastroRouteWithChildren = CadastroRoute._addFileChildren(
  CadastroRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AvaliacoesRoute: AvaliacoesRoute,
  CadastroRoute: CadastroRouteWithChildren,
  ClubesRoute: ClubesRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  ManualRoute: ManualRoute,
  SuporteRoute: SuporteRoute,
  CandidatosCandidatoIdRoute: CandidatosCandidatoIdRoute,
  PeneirasPeneiraIdRoute: PeneirasPeneiraIdRoute,
  PeneirasCriarRoute: PeneirasCriarRoute,
  CandidatosIndexRoute: CandidatosIndexRoute,
  PeneirasIndexRoute: PeneirasIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
